on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrif56ywufwbb6i.azurecr.io
        username: ${{ secrets.acr_acrif56ywufwbb6i_username }}
        password: ${{ secrets.acr_acrif56ywufwbb6i_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrif56ywufwbb6i.azurecr.io/vipulakscluster2:${{ github.sha }}
        docker push acrif56ywufwbb6i.azurecr.io/vipulakscluster2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulakscluster2bbd3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulakscluster2bbd3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulakscluster2bbd3
        container-registry-url: acrif56ywufwbb6i.azurecr.io
        container-registry-username: ${{ secrets.acr_acrif56ywufwbb6i_username }}
        container-registry-password: ${{ secrets.acr_acrif56ywufwbb6i_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: chart
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:acrif56ywufwbb6i.azurecr.io/vipulakscluster2
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:vipulaksclusdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulakscluster2bbd3
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          acrif56ywufwbb6i.azurecr.io/vipulakscluster2:${{ github.sha }}
        imagepullsecrets: |
          vipulaksclusdockerauth