on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaacr_username }}
        password: ${{ secrets.acr_abhisheaacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t abhisheaacr.azurecr.io/vipulakscluster:${{ github.sha }}
        docker push abhisheaacr.azurecr.io/vipulakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulakscluster5c6e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulakscluster5c6e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulakscluster5c6e
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaacr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaacr_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulakscluster5c6e
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress.yml
        images: |
          abhisheaacr.azurecr.io/vipulakscluster:${{ github.sha }}
        imagepullsecrets: |
          vipulaksclusdockerauth